# ----- Config for Rqi / Email Utility  -----
# Outlook (tenantId: csussandbox.onmicrosoft.com OR common)
outlook.clientId=**********
outlook.tenantId=common

outlook.tokenCacheName=graph-cache
outlook.tokenCacheFile=config/auth_cache/outlook_token_cache.json
outlook.graphScopes=User.Read,Mail.Read,Calendars.ReadWrite,Mail.Send

# Google Sheets
google.credentialsFile=config/credentials.json
google.spreadsheetAha=1Mz9m5x8tLihEdpJfmv8NZYdYkxokqzCiGeZ48lB_c2Y
google.spreadsheetRqi=18tVdlycK7cC-KNFBU_GQza7ihqdvyyjV-Y_Dh4cd00k
google.sheetNameAha=Sheet1
google.sheetNameRqi=Sheet1

# RQI SFTP
rqi.enabled=true
rqi.host=rqi1stop-sftp-preprod.rqi1stop.com
rqi.port=6239
rqi.username=116286
rqi.password=**********
rqi.remoteDir=/uploads/116286
rqi.filename=preprod_cl.csv

# Local files
file.msgIds=resources/msg_id.txt
file.emailDump=resources/email_dump.txt
file.rqiCsv=resources/preprod_cl.csv
file.ahaCsv=resources/aha.csv

# App runtime
app.runContinuously=true
app.runInterval=30

# Email limits
email.maxAge=14
email.maxCount=50

# ----- Config for AHA Automation -----
# AhaScraper.java and GoogleSheetsWriter.java use configs from Rqi / Email Utility
# AHA login
aha.email=Sacstatecpr@outlook.com
aha.password=**********

# App runtime
aha.runContinuously=true
aha.runInterval=30
aha.headlessMode=true

# AHA filters (for date range: 0 = today; 1 = tmr; -1 = yesterday)
aha.instructor=All
aha.organization=Sac State
aha.startOffsetDays=0
aha.endOffsetDays=0

# ----- Config for Outlook Event Creator -----
# Reuse some configs from Rqi / Email Utility: outlook.clientId, outlook.tenantId, email.maxCount
calendar.tokenCacheFile=config/auth_cache/calendar_msal_cache.json
# App runtime
calendar.runContinuously=true
calendar.runInterval=30

# Calendar
calendar.timeZone=America/Los_Angeles

# Local files
calendarFile.seenIds=resources/calendar_seen_ids.txt

# ----- Config for Reminder Module -----
reminder.dryRun=true

reminder.tokenCacheFile=config/auth_cache/reminder_msal_cache.json

# App runtime (seconds)
reminder.runContinuously=true
reminder.runInterval=30

# Registration reminders
reminder.registration.enabled=true
reminder.registration.resendAfterDays=7

reminder.registration.subject=Complete Your AHA Course Registration
reminder.registration.template=resources/email_templates/registration_template.txt